#!/bin/bash -e



#Note: may want to check for valid dcast username and password first

# The following files must be obtained from PubTator or MeSH and put in
# a download/ directory

# desc2019.xml      ftp://nlmpubs.nlm.nih.gov/online/mesh/MESH_FILES/xmlmesh/ 
# supp2019.xml         
# chemical2pubtator   https://www.ncbi.nlm.nih.gov/CBBresearch/Lu/Demo/PubTator/ 
# disease2pubtator     
# gene2pubtator        
# mutation2pubtator    

# mysql connector needs to be installed: pip install  mysql-connector

if [ $# -ne 2 ]
    then
    echo "Usage: processFiles dcast.username dcast.password"
    echo "Processes pubtator and mesh files in download/ and creates:
    download/processed - the processed data
    download/completed - the original files"
    exit -1
fi

echo 
echo "Checking download directory for invalid files..."

# commands to process various scripts
cmdMesh="python mesh/xml_to_file.py download/desc2019.xml 
                download/processed/desc2019.txt descriptor"
cmdSupp="python mesh/xml_to_file.py download/supp2019.xml 
                download/processed/supp2019.txt supplementary"

cmdChem="python pubtator/processChemical2pubtator.py
                download/processed/desc2019.txt 
                download/processed/supp2019.txt 
                download/chemical2pubtator 
                download/processed/chemical2pubtator_processed"
cmdDisease="python pubtator/processDisease2pubtator.py $1 $2 
                download/disease2pubtator 
                download/processed/disease2pubtator_processed"
cmdGenes="python pubtator/processGene2pubtator.py 
                download/gene2pubtator 1 
                download/processed/gene2pubtator_processed
				data_for_mysql/HumanGeneIDs.csv"
cmdMutation="Rscript pubtator/processMutations2pubtator.R download/mutation2pubtator download/processed/mutation2pubtator_processed"


declare -a files
declare -a cmd
files[0]="desc2019.xml";         cmd[0]=$cmdMesh
files[1]="supp2019.xml";         cmd[1]=$cmdSupp
files[2]="chemical2pubtator";    cmd[2]=$cmdChem
files[3]="disease2pubtator";     cmd[3]=$cmdDisease
files[4]="gene2pubtator";        cmd[4]=$cmdGenes
files[5]="mutation2pubtator";    cmd[5]=$cmdMutation


# check for required directories
mkdir -p download/processed/
mkdir -p download/completed/
required=(download download/processed download/completed)

for i in "${required[@]}"
do
    if [ ! -e $i ]; then
        echo "Error: the following required directory was not found: $i"
        exit
    fi
done


# check for invalid files
invalid=""
for entry in download/*
do
  file1="$(basename "$entry")"

  if [[ " ${files[@]} " =~ "$file1" ]]; then
   # do nothing
   :
  elif [ $file1 != "processed" ] && [ $file1 != "completed" ]; then
    invalid="$invalid $file1"
  fi
done

if [ "$invalid" != '' ]
then
    echo "Error: invalid files found: $invalid"
    exit
fi


# process files
total=${#files[*]}
#total=3
for (( i=0; i<=$(( $total -1 )); i++ ))
    do
    ff="download/${files[i]}"
        if [ -f $ff ]; then
            echo "Processing file: $ff"
            echo "cmd: ${cmd[i]}"
            echo
            ${cmd[i]}
            echo "Moving $ff to download/completed/"
            mv $ff "download/completed/${files[i]}"
            echo 
        else
            echo "Note: $ff not found, and will not be processed" 
        fi
done

